# Generated by Django 5.2.3 on 2025-06-25 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_servicerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='service_request_images/'),
        ),
    ]
