# Generated by Django 5.2.3 on 2025-06-25 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_servicerequestimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='image',
        ),
    ]
