# Generated by Django 5.2.3 on 2025-06-25 02:19

import client.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_remove_servicerequest_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequestimage',
            name='image',
            field=models.ImageField(upload_to=client.models.service_request_image_path),
        ),
    ]
