# Generated by Django 5.2.3 on 2025-06-30 21:10

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_alter_servicerequest_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('industry', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Construction', 'Construction'), ('Plumbing', 'Plumbing'), ('Electrical', 'Electrical'), ('Landscaping', 'Landscaping'), ('Painting', 'Painting'), ('Other', 'Other')], max_length=59, null=True)),
                ('services', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Renovation', 'Renovation'), ('Repair', 'Repair'), ('Installation', 'Installation'), ('Consultation', 'Consultation'), ('Maintenance', 'Maintenance'), ('Inspection', 'Inspection'), ('Design', 'Design'), ('Other', 'Other')], max_length=79, null=True)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to='client.userprofile')),
            ],
        ),
    ]
