# Generated by Django 5.2.3 on 2025-07-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_chatroom_message'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='room_name',
            field=models.CharField(default=3, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
